language: ruby
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=62c8432c7209b62a8fe7638d88a2f9ce097c51c09ef48f12c1f8625616436931

cache: bundler

before_install:
  - sudo apt-get install -qq graphviz
  - gem update --system
  - gem install bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

rvm:
  - 2.5
  - 2.4
  - 2.3

gemfile:
  - gemfiles/activerecord-4.1.Gemfile
  - gemfiles/activerecord-4.2.Gemfile
  - gemfiles/activerecord-5.0.Gemfile
  - gemfiles/activerecord-5.1.Gemfile
  - gemfiles/activerecord-5.2.Gemfile


matrix:
  exclude:
    # RUBY 2.3
  - rvm: 2.3
    gemfile: gemfiles/activerecord-5.0.Gemfile

  - rvm: 2.3
    gemfile: gemfiles/activerecord-5.1.Gemfile

  - rvm: 2.3
    gemfile: gemfiles/activerecord-5.2.Gemfile

    # RUBY 2.4
  - rvm: 2.4
    gemfile: gemfiles/activerecord-4.1.Gemfile

    # RUBY 2.5
  - rvm: 2.5
    gemfile: gemfiles/activerecord-4.1.Gemfile
