before_install:
  - sudo apt-get install -qq graphviz

rvm:
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.rails-edge

matrix:
  include:
    # legacy build: Ruby 1.8.7, Rails 2.3, less features, smaller test set
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-2.3.x
      # running a smaller test set for old Rails and Ruby
      script: rake test_without_new_versions

    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.x

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-3.x
